apiVersion: opentestfactory.org/v1
kind: Workflow
metadata:
  name: "Playwright (Node) with provider demo"
jobs:
  e2e:
    runs-on: [linux,playwright] 
    steps:
      - name: ソースコードの取得
        uses: "actions/checkout@v2"
        with:
          repository: "https://github.com/mima3/research_tms"
          ref: "main"

      # 依存解決（tests/ に package.json がある前提）
      - name: Install deps
        variables:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
        run: |
          cd research_tms/annex/opentestfactory/docker/playwright/workspace
          ls -lt
          pwd
          echo ${OPENTF_WORKSPACE}
          npm ci || npm i
          npx playwright install --with-deps

      # 公式 Playwright プロバイダーで実行
      - uses: playwright/npx@v1
        with:
          test: ${OPENTF_WORKSPACE}/research_tms/annex/opentestfactory/docker/playwright/workspace/tests/*.spec.ts
          reporters: ['junit','html']   # pw_junit_report.xml と index.html を自動添付
        working-directory: ${OPENTF_WORKSPACE}/research_tms/annex/opentestfactory/docker/playwright/workspace
