apiVersion: opentestfactory.org/v1
kind: Workflow
metadata:
  name: "Playwright (Node) with provider demo"
jobs:
  e2e:
    runs-on: [linux,playwright] 
    steps:
      # 依存解決（tests/ に package.json がある前提）
      - name: Install deps
        run: |
          cd /workspace/
          npm ci || npm i

      - name: Sync Playwright browsers
        variables:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "0"
        run: |
          cd /workspace/
          npx playwright install --with-deps

      # 公式 Playwright プロバイダーで実行
      - uses: playwright/npx@v1
        with:
          test: /workspace/tests/*.spec.ts
          reporters: ['junit','html']   # pw_junit_report.xml と index.html を自動添付
        working-directory: /workspace/tests
