metadata:
  name: test-agent
jobs:
  unit_test:
    runs-on: [linux,pytest]
    steps:
      - name: ソースコードの取得
        uses: "actions/checkout@v2"
        with:
          repository: "https://github.com/mima3/test_asyncio"
          ref: "main"
      - name: 初期設定
        run: pip install --no-input -q aiofiles
      - name: テスト実行
        run: |
          cd test_asyncio/py313
          pytest -q --junitxml=junit.xml -o junit_family=xunit2 -o junit_duration_report=call test
      - name: 結果のアップロード
        run: |
          echo "::upload type=application/xml,name=junit.xml::`pwd`/test_asyncio/py313/junit.xml"
