services:
  orchestrator:
    image: opentestfactory/allinone:latest
    container_name: orchestrator
    restart: unless-stopped
    ports:
      - "7774:7774"   # receptionist (POST /workflows)
      - "7775:7775"   # observer (GET /workflows/<id>)
      - "7776:7776"   # killswitch
      - "7796:7796"   # insights
      - "38368:38368" # eventbus
      - "34537:34537" # localstore
      - "24368:24368" # agent channel
      - "10093:10093"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:7774/workflows"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - ./trusted_keys:/etc/squashtf
    environment:
      DEBUG: DEBUG
      OPENTF_DEBUG: DEBUG


  pytest-agent:
    build: ./pytest
    container_name: pytest-agent
    depends_on: [orchestrator]
    environment:
      TOKEN: ${TOKEN}
    command: >
      sh -lc "opentf-agent --tags linux,pytest --host http://orchestrator --port 24368
      --token \"$TOKEN\" --verify false --script_path /tmp"

  playwright-agent:
    build: ./playwright
    container_name: playwright-agent
    depends_on: [orchestrator]
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - ./playwright/workspace:/workspace:rw
    command: >
      sh -lc "opentf-agent --tags linux,playwright --host http://orchestrator --port 24368
      --token \"$TOKEN\" --verify false --script_path /tmp"
