"""
This type stub file was generated by pyright.
"""

from xmlrpc.client import SafeTransport, ServerProxy, Transport

VERBOSE = ...
_PYTHON_VERSION = ...
class TCMSProxy(ServerProxy):
    def __getattr__(self, name): # -> _Method:
        ...
    


class CookieTransport(Transport):
    """A subclass of xmlrpc.client.Transport that supports cookies."""
    scheme = ...
    user_agent = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def send_headers(self, connection, headers): # -> None:
        ...
    
    def parse_response(self, response): # -> tuple[_Marshallable, ...]:
        ...
    


class SafeCookieTransport(SafeTransport, CookieTransport):
    """SafeTransport subclass that supports cookies."""
    scheme = ...


class KerbTransport(SafeCookieTransport):
    """Handles GSSAPI Negotiation (SPNEGO) authentication."""
    def get_host_info(self, host): # -> tuple[str, list[tuple[str, str]], dict[str, str]]:
        ...
    
    def make_connection(self, host): # -> HTTPSConnection:
        """
        Return an individual HTTPS connection for each request.

        Fix https://bugzilla.redhat.com/show_bug.cgi?id=735937
        """
        ...
    


def get_hostname(url):
    """
    Performs the same parsing of the URL as the Transport
    class and returns only the hostname which is used to
    generate the service principal name for Kiwi TCMS and
    the respective Authorize header!
    """
    ...

class TCMSXmlrpc:
    """
    XML-RPC client for username/password authentication.
    """
    session_cookie_name = ...
    transport = ...
    def __init__(self, username, password, url) -> None:
        ...
    
    def login(self): # -> None:
        ...
    


class TCMSKerbXmlrpc(TCMSXmlrpc):
    """
    XML-RPC client for server deployed with python-social-auth-kerberos.

    Should also work for servers deployed with mod_auth_gssapi but
    that is not supported nor guaranteed!
    """
    transport = ...
    def __init__(self, username, password, url) -> None:
        ...
    


